"""Shared helpers for every analysis script: folders, loading sessions, safety checks.

Folder layout (SPEC.md section 7). Every script takes --data and --results so
the same code can run on the real data (the defaults) or on the synthetic
demo data in analysis/demo/:

    <data>/raw/<session_id>.csv        one row per sample (see data/README.md)
    <data>/raw/<session_id>.json       metadata sidecar written by logger.py
    <data>/processed/                  generated: truth, estimates
    <data>/splits.json                 train / validation / test sessions
    <results>/figures/, <results>/tables/   generated by the scripts
"""
from __future__ import annotations

import json
import subprocess
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parent.parent
DEFAULT_DATA = REPO / "data"
DEFAULT_RESULTS = REPO / "results"

# The blocks of the experiment protocol (SPEC.md section 5).
BLOCKS = {
    "A": "static noise",
    "B": "clean motion",
    "C": "variance bursts",
    "D": "frozen bursts",
    "E": "physical faults",
    "F": "measured-parameter bursts",
    "G": "integrated live run",
}

# Codes in the recovery_event column. They are the same numbers as the Spec 2
# guard's EventType (lib/sel_guard/src/guard_types.h), so one labelling rule
# works for both firmware builds.
EVENT_NONE = 0
EVENT_SEL_TRIP = 1
EVENT_SEL_LOCKOUT = 2
EVENT_SENSOR_FAULT = 3
EVENT_LADDER_STEP = 4
EVENT_SENSOR_RECOVERED = 5
EVENT_SENSOR_FAILED = 6
EVENT_CURRENT_SENSOR_ERROR = 7

MISSING = -1  # value of raw_mm / clean_mm / faulted_mm when there was no usable reading


def git_commit() -> str:
    """Short commit hash of this repository (with -dirty if files changed)."""
    try:
        rev = subprocess.check_output(["git", "rev-parse", "--short=10", "HEAD"], cwd=REPO, text=True,
                                      stderr=subprocess.DEVNULL).strip()
        dirty = subprocess.check_output(["git", "status", "--porcelain", "--untracked-files=no"], cwd=REPO,
                                        text=True, stderr=subprocess.DEVNULL).strip()
        return rev + ("-dirty" if dirty else "")
    except Exception:
        return "unknown"


# ---------------------------------------------------------------------------
# Folders
# ---------------------------------------------------------------------------
class Paths:
    """All folders a script reads from or writes to."""

    def __init__(self, data: Path | str = DEFAULT_DATA, results: Path | str = DEFAULT_RESULTS):
        self.data = Path(data).resolve()
        self.results = Path(results).resolve()
        self.raw = self.data / "raw"
        self.processed = self.data / "processed"
        self.splits = self.data / "splits.json"
        self.figures = self.results / "figures"
        self.tables = self.results / "tables"

    def make_output_dirs(self):
        for p in (self.processed, self.figures, self.tables):
            p.mkdir(parents=True, exist_ok=True)


def add_path_args(parser):
    """Add the standard --data / --results options to an argparse parser."""
    parser.add_argument("--data", default=str(DEFAULT_DATA), help="data folder (default: data/)")
    parser.add_argument("--results", default=str(DEFAULT_RESULTS), help="results folder (default: results/)")
    return parser


def is_real_results_dir(results: Path) -> bool:
    return Path(results).resolve() == DEFAULT_RESULTS.resolve()


def check_no_synthetic_in_results(paths: Paths, metas: list[dict]):
    """Refuse to write anything made from synthetic data into the real results/ folder.

    SPEC.md section 9, rule 4: synthetic data may only be used in tests/ and analysis/demo/,
    never in results/.
    """
    if not is_real_results_dir(paths.results):
        return
    bad = [m.get("session_id", "?") for m in metas if m.get("synthetic", False)]
    if bad:
        raise SystemExit(
            f"Refusing to write to {paths.results}: sessions {bad[:5]} are marked synthetic. "
            "Synthetic data may only be analysed with --results analysis/demo/output."
        )


# ---------------------------------------------------------------------------
# Sessions
# ---------------------------------------------------------------------------
def list_sessions(paths: Paths, block: str | None = None) -> list[str]:
    """Session ids found in <data>/raw, optionally only one block (A-G)."""
    out = []
    for js in sorted(paths.raw.glob("*.json")):
        if not (js.with_suffix(".csv")).exists():
            continue
        meta = json.loads(js.read_text())
        if block is None or meta.get("block") == block:
            out.append(js.stem)
    return out


def load_meta(paths: Paths, session_id: str) -> dict:
    return json.loads((paths.raw / f"{session_id}.json").read_text())


def load_session(paths: Paths, session_id: str) -> tuple[pd.DataFrame, dict]:
    """Read one session: the CSV rows and the JSON sidecar.

    Adds two helper columns:
      t_s       time in seconds from the first row
      has_meas  True where faulted_mm holds a usable measurement
    """
    # round_trip: parse every number to exactly the double the firmware used
    # (pandas' default fast parser can be off in the last bit).
    df = pd.read_csv(paths.raw / f"{session_id}.csv", float_precision="round_trip")
    meta = load_meta(paths, session_id)
    df["t_s"] = (df["t_us"] - df["t_us"].iloc[0]) / 1e6
    if "faulted_mm" in df:
        df["has_meas"] = df["faulted_mm"] >= 0
    return df, meta


def load_splits(paths: Paths) -> dict:
    """{"train": [...], "validation": [...], "test": [...]} (see analysis/make_splits.py)."""
    if not paths.splits.exists():
        raise SystemExit(f"{paths.splits} not found. Run: python analysis/make_splits.py --data {paths.data}")
    return json.loads(paths.splits.read_text())


def sessions_in(paths: Paths, split: str, blocks: str | list[str]) -> list[str]:
    """Sessions that are in one split ("train"/"validation"/"test") and in the given blocks."""
    splits = load_splits(paths)
    want = set(blocks)
    out = []
    for sid in splits.get(split, []):
        js = paths.raw / f"{sid}.json"
        if js.exists() and json.loads(js.read_text()).get("block") in want:
            out.append(sid)
    return out


def load_truth(paths: Paths, session_id: str) -> pd.DataFrame:
    """Ground truth written by ground_truth.py (one row per CSV row)."""
    p = paths.processed / "truth" / f"{session_id}_truth.csv"
    if not p.exists():
        raise SystemExit(f"{p} not found. Run: python analysis/ground_truth.py --data {paths.data}")
    return pd.read_csv(p)


def write_json(path: Path, obj):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2, default=_json_default) + "\n")


def _json_default(o):
    if isinstance(o, (np.integer,)):
        return int(o)
    if isinstance(o, (np.floating,)):
        return float(o)
    if isinstance(o, np.ndarray):
        return o.tolist()
    raise TypeError(type(o))


def provenance(paths: Paths, sessions: list[str]) -> dict:
    """What every results file records about where it came from."""
    metas = [load_meta(paths, s) for s in sessions]
    return {
        "analysis_git_commit": git_commit(),
        "firmware_commits": sorted({m.get("firmware", {}).get("fw_commit", "unknown") for m in metas}),
        "sessions": sessions,
        "synthetic": any(m.get("synthetic", False) for m in metas),
    }
